[project]
name = "search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Akash Singhal", email = "akigupta131@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.1.0",
    "pandas>=3.0.6",
    "pyvespa>=1.2.8",
]

[project.scripts]
search = "search:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
